### ISSUE TITLE
bug: can't install tagged versions with `yarn`

### ISSUE THREAD

**Issue by marlalain** [t3-oss/create-t3-app#454] opened 2022-09-16 08:16 UTC
### Provide environment information

6.0.0-next.2af4bc9

### Describe the bug

Can't install the project with Yarn version 2.

### To reproduce

```sh
npx create-t3-app@next something
cd something
yarn install
```

```
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 6s 756ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ wrappy@npm:1.0.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yallist@npm:4.0.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yocto-queue@npm:0.1.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ zod@npm:3.19.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ typescript@npm:4.7.4 can't be found in the cache and will be fetched from the remote registry
➤ YN0066: │ typescript@patch:typescript@npm%3A4.7.4#builtin<compat/typescript>::version=4.7.4&hash=8133ad: Cannot apply hunk #2 (set enableInlineHunks for details)
➤ YN0000: └ Completed in 32s 30ms
➤ YN0000: Failed with errors in 38s 791ms```

### Additional information

yarn --version
2.4.3

node --version
v16.17.0

npm --version
8.15.0

**Comment by minsk-dev** [comment] 2022-09-16 08:19
`npm`, `pnpm` and `yarn@1` work. Going to create a PR warning the user (if they are using yarn@2 or yarn@3) that installation may fail

**Comment by c-ehrlich** [comment] 2022-09-16 08:32
we already have a check for yarn 3. maybe you can just expand it to also check for yarn 2?

**Comment by minsk-dev** [comment] 2022-09-16 09:27
I did this, but I don't know how I'm supposed to test this https://github.com/minsk-dev/create-t3-app/commit/965cd968375872ca406b9e4e77add7afbb708722 @c-ehrlich

**Comment by c-ehrlich** [comment] 2022-09-16 10:35
When I built the yarn 3 check I did manual testing, used different VMs where I had different package managers installed

**Comment by juliusmarminge** [comment] 2022-09-16 14:11
```
npx create-t3-app@next something
cd something
yarn install
```

this seems weird. why would you npx then yarn install?

**Comment by minsk-dev** [comment] 2022-09-16 14:19
> 

Does it matter? The generated project is supposed to be the same. Also, looks like `yarn@2` can't run the CLI.

```
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 4s 950ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ sort-package-json@npm:1.57.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ tinycolor2@npm:1.4.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ tinygradient@npm:1.1.5 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ type-fest@npm:1.4.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ wrap-ansi@npm:8.0.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0000: └ Completed in 1s 276ms
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed
➤ YN0000: Done in 6s 328ms

/Users/anon/.yarn/berry/cache/create-t3-app-npm-6.0.0-next.2af4bc9-8a4bcf0cd8-7.zip/node_modules/create-t3-app/dist/index.js:2
import he from"path";import ye from"fs-extra";import b from"path";import J from"fs-extra";import D from"path";import{fileURLToPath as Oe}from"url";var Ne=Oe(import.meta.url),Me=D.dirname(Ne),c=D.join(Me,"../"),$=`   ___ ___ ___   __ _____ ___   _____ ____    __   ___ ___
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1055:15)
    at Module._compile (node:internal/modules/cjs/loader:1090:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.external_module_.Module._load (/private/var/folders/mc/f08wsz9x4ns8fvx3b3bb3x740000gp/T/xfs-5673fae3/dlx-46995/.pnp.js:6021:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47```

**Comment by juliusmarminge** [comment] 2022-09-16 14:22
well the problem with yarn 3 is that you can't scaffold the project. you should test running the cli with it. if you can't install dependencies with `yarn install` I can't see how it's CT3A's fault without seeing the actual error message 🤔 

> Also, looks like yarn@2 can't run the CLI.

Yes this is more interesting and should be tagged.

**Comment by juliusmarminge** [comment] 2022-09-16 14:23
> `SyntaxError: Cannot use import statement outside a module`

Wow yarn is weird...

**Comment by minsk-dev** [comment] 2022-09-16 14:28
> > `SyntaxError: Cannot use import statement outside a module`
> 
> Wow yarn is weird...

Probably because of the way we are making the bundle right now. https://github.com/t3-oss/create-t3-app/blob/main/package.json#L9

**Comment by minsk-dev** [comment] 2022-09-19 10:58
Update: Looks like you can't use `yarn@1` now.

```shell
yarn create t3-app@next
```

```
yarn create v1.22.19
warning package.json: No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...

success Installed "create-t3-app@6.0.0-next.1d84e9f" with binaries:
      - create-t3-app
/bin/sh: /Users/anon/.yarn/bin/create-t3-app@next: No such file or directory
error Command failed.
Exit code: 127
Command: /Users/anon/.yarn/bin/create-t3-app@next
Arguments: asdf
Directory: /private/tmp
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.```

**Comment by juliusmarminge** [comment] 2022-09-19 11:00
> Update: Looks like you can't use `yarn@1` now.
> 
> 
> 
> ```shell
> 
> yarn create t3-app@next
> 
> ```
> 
> 
> 
> ```
> 
> yarn create v1.22.19
> 
> warning package.json: No license field
> 
> [1/4] 🔍  Resolving packages...
> 
> [2/4] 🚚  Fetching packages...
> 
> [3/4] 🔗  Linking dependencies...
> 
> [4/4] 🔨  Building fresh packages...
> 
> 
> 
> success Installed "create-t3-app@6.0.0-next.1d84e9f" with binaries:
> 
>       - create-t3-app
> 
> /bin/sh: /Users/anon/.yarn/bin/create-t3-app@next: No such file or directory
> 
> error Command failed.
> 
> Exit code: 127
> 
> Command: /Users/anon/.yarn/bin/create-t3-app@next
> 
> Arguments: asdf
> 
> Directory: /private/tmp
> 
> Output:
> 
> 
> 
> info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
> 
> ```
> 
> 
> 
> 

I don't think yarn ever played nice with version tags?

**Comment by minsk-dev** [comment] 2022-09-19 11:01
I believe this was working before. I don't think any major version of yarn works now

**Comment by juliusmarminge** [comment] 2022-09-19 11:03
> I believe this was working before. I don't think any major version of yarn works now

Not sure what the difference is, does @beta tag work?

**Comment by minsk-dev** [comment] 2022-09-19 11:05
> > I believe this was working before. I don't think any major version of yarn works now
> 
> Not sure what the difference is in terms of the cli, does @beta tag work? Maybe yarns binaries aren’t updated yet?

Also doesn't work. Now, I'm not sure if this was working before... 🤔

**Comment by juliusmarminge** [comment] 2022-09-19 11:07
> > > I believe this was working before. I don't think any major version of yarn works now
> 
> > 
> 
> > Not sure what the difference is in terms of the cli, does @beta tag work? Maybe yarns binaries aren’t updated yet?
> 
> 
> 
> Also doesn't work. Now, I'm not sure if this was working before... 🤔

I think when I've tested beta and next with yarn it doesn't like the version tag at the end for some reason.

Just use pnpm or npm I guess

**Comment by minsk-dev** [comment] 2022-09-19 11:07
@c-ehrlich A PR warning against yarn? What do you think? I could do it

**Comment by juliusmarminge** [comment] 2022-09-19 11:09
> @c-ehrlich A PR warning against yarn? What do you think? I could do it

I don't think you even get to that point when you try the tags? Like even a log at line1 wouldn't be printed I'm pretty sure

**Comment by minsk-dev** [comment] 2022-09-19 11:10
It looks like it's trying to run `create-t3-app@next`. With the `@next` thing

**Comment by juliusmarminge** [comment] 2022-09-19 11:12
> It looks like it's trying to run `create-t3-app@next`. With the `@next` thing

Is there another way to run tagged scripts (like yarn create t3-app --tag next or smth)?Some other cli that we can test on? I can't see how this can be caused by us?

**Comment by minsk-dev** [comment] 2022-09-19 11:13
Doesn't look like it

```sh
yarn create --help
```

```
warning package.json: No license field

  Usage: yarn [command] [flags]

  Creates new projects from any create-* starter kits.

  Options:

    -v, --version                       output the version number
    --no-default-rc                     prevent Yarn from automatically detecting yarnrc and npmrc files
    --use-yarnrc <path>                 specifies a yarnrc file that Yarn should use (.yarnrc only, not .npmrc) (default: )
    --verbose                           output verbose messages on internal operations
    --offline                           trigger an error if any required dependencies are not available in local cache
    --prefer-offline                    use network only if dependencies are not available in local cache
    --enable-pnp, --pnp                 enable the Plug'n'Play installation
    --disable-pnp                       disable the Plug'n'Play installation
    --strict-semver
    --json                              format Yarn log messages as lines of JSON (see jsonlines.org)
    --ignore-scripts                    don't run lifecycle scripts
    --har                               save HAR output of network traffic
    --ignore-platform                   ignore platform checks
    --ignore-engines                    ignore engines check
    --ignore-optional                   ignore optional dependencies
    --force                             install and build packages even if they were built before, overwrite lockfile
    --skip-integrity-check              run install without checking if node_modules is installed
    --check-files                       install will verify file tree of packages for consistency
    --no-bin-links                      don't generate bin links when setting up packages
    --flat                              only allow one version of a package
    --prod, --production [prod]
    --no-lockfile                       don't read or generate a lockfile
    --pure-lockfile                     don't generate a lockfile
    --frozen-lockfile                   don't generate a lockfile and fail if an update is needed
    --update-checksums                  update package checksums from current repository
    --link-duplicates                   create hardlinks to the repeated modules in node_modules
    --link-folder <path>                specify a custom folder to store global links
    --global-folder <path>              specify a custom folder to store global packages
    --modules-folder <path>             rather than installing modules into the node_modules folder relative to the cwd, output them here
    --preferred-cache-folder <path>     specify a custom folder to store the yarn cache if possible
    --cache-folder <path>               specify a custom folder that must be used to store the yarn cache
    --mutex <type>[:specifier]          use a mutex to ensure only one yarn instance is executing
    --emoji [bool]                      enable emoji in output (default: true)
    -s, --silent                        skip Yarn console logs, other types of logs (script output) will be printed
    --cwd <cwd>                         working directory to use (default: /private/tmp)
    --proxy <host>
    --https-proxy <host>
    --registry <url>                    override configuration registry
    --no-progress                       disable progress bar
    --network-concurrency <number>      maximum number of concurrent network requests
    --network-timeout <milliseconds>    TCP timeout for network requests
    --non-interactive                   do not show interactive prompts
    --scripts-prepend-node-path [bool]  prepend the node executable dir to the PATH in scripts
    --no-node-version-check             do not warn when using a potentially unsupported Node version
    --focus                             Focus on a single workspace by installing remote copies of its sibling workspaces.
    --otp <otpcode>                     one-time password for two factor authentication
    -h, --help                          output usage information
  Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
```

**Comment by juliusmarminge** [comment] 2022-09-19 11:15
Can you do `yarn dlx create-t3-app@next`?

**Comment by minsk-dev** [comment] 2022-09-19 11:39
@juliusmarminge Command not found

**Comment by minsk-dev** [comment] 2022-09-19 11:40
`yarn create` is made for this case. I don't know why they don't handle tags. Will take a look at their issues and see if I can find something

**Comment by juliusmarminge** [comment] 2022-09-19 15:06
> `yarn create` is made for this case. I don't know why they don't handle tags. Will take a look at their issues and see if I can find something

As you might have guessed i wasnt at my PC, nor do I use yarn xD

If you find a fix feel free to PR but I won't personally put any time into it. Maybe some yarn users are interested?

**Comment by c-ehrlich** [comment] 2022-09-19 20:16
if its not possible to use version tags with yarn 1 then i don't see a reason to put a warning. 

personally even when i use yarn as my package manager, i scaffold with npx

**Comment by minsk-dev** [comment] 2022-09-20 08:19
Looks like you can specify `yarn` versions on the `package.json`: https://github.com/calcom/cal.com/blob/main/package.json#L97.

---

> if its not possible to use version tags with yarn 1 then i don't see a reason to put a warning.
> 
> personally even when i use yarn as my package manager, i scaffold with npx

I think a warning on the project's README should be enough?

**Comment by juliusmarminge** [comment] 2022-09-20 09:06
> Looks like you can specify `yarn` versions on the `package.json`: https://github.com/calcom/cal.com/blob/main/package.json#L97.
> 
> > if its not possible to use version tags with yarn 1 then i don't see a reason to put a warning.
> > personally even when i use yarn as my package manager, i scaffold with npx
> 
> I think a warning on the project's README should be enough?

We can do all of this i guess:

- restrict yarn version in package.json
- update isntallation guide (README and Docs) and put a note that if you're using yarn, scaffold with npm and choose noInstall and install deps on your own 🤔

**Comment by minsk-dev** [comment] 2022-09-20 09:24
I can do that. Will open a PR later

**Comment by nexxeln** [comment] 2022-09-28 13:30
> I can do that. Will open a PR later

Are you still free to make a PR?

**Comment by minsk-dev** [comment] 2022-09-28 16:55
> > I can do that. Will open a PR later
> 
> Are you still free to make a PR?

I don't have the time to test this right now. Writing is simple, but I would have to mess with my packages to test this

**Comment by nexxeln** [comment] 2022-10-11 16:06
> We moved to using `next` as the default branch, is this issue still relevant? I tried `yarn create t3-app` and with Yarn@1 and it works as expected. If this issue still needs some testing, I can take a look.

I agree with @juliusmarminge and think we should just leave it open. There's some issues with yarn 2 and 3 and if someone knows how to fix them then they can know about this issue.

**Comment by juliusmarminge** [comment] 2022-10-11 20:44
Putting the `wontfix` label on. If anyone knows a fix without digging too hard feel free but don't your time on it 🙏

**Comment by arugaz** [comment] 2022-10-31 19:50
i just tried and had no problems [pict](https://prnt.sc/Mi3TW-fXoXYJ)

**Comment by juliusmarminge** [comment] 2022-10-31 19:52
> i just tried and had no problems [pict](https://prnt.sc/Mi3TW-fXoXYJ)

You're just running the normal, problem is when you add a tag like `yarn create t3-app@beta`

**Comment by arugaz** [comment] 2022-10-31 21:35
> > i just tried and had no problems [pict](https://prnt.sc/Mi3TW-fXoXYJ)
> 
> You're just running the normal, problem is when you add a tag like `yarn create t3-app@beta`

i tried yarn create t3-app@next and it works [pict](https://prnt.sc/Z8AdQfhOmbGS)

- yarn v3.2.4
- node v16.16.0
- npm v8.19.2

**Comment by juliusmarminge** [comment] 2022-11-24 20:24
<img width="593" alt="CleanShot 2022-11-24 at 21 24 05@2x" src="https://user-images.githubusercontent.com/51714798/203859099-a54670d8-14cd-4e2c-b582-230a84387357.png">

Maybe we need to update the issue title then. Yarn v1 doesn't work

**Comment by abdlmutii** [comment] 2023-03-18 17:59
> ### Provide environment information
> 6.0.0-next.2af4bc9
> 
> ### Describe the bug
> Can't install the project with Yarn version 2.
> 
> ### To reproduce
> ```shell
> npx create-t3-app@next something
> cd something
> yarn install
> ```
> 
> ```
> ➤ YN0000: ┌ Resolution step
> ➤ YN0000: └ Completed in 6s 756ms
> ➤ YN0000: ┌ Fetch step
> ➤ YN0013: │ wrappy@npm:1.0.2 can't be found in the cache and will be fetched from the remote registry
> ➤ YN0013: │ yallist@npm:4.0.0 can't be found in the cache and will be fetched from the remote registry
> ➤ YN0013: │ yocto-queue@npm:0.1.0 can't be found in the cache and will be fetched from the remote registry
> ➤ YN0013: │ zod@npm:3.19.1 can't be found in the cache and will be fetched from the remote registry
> ➤ YN0013: │ typescript@npm:4.7.4 can't be found in the cache and will be fetched from the remote registry
> ➤ YN0066: │ typescript@patch:typescript@npm%3A4.7.4#builtin<compat/typescript>::version=4.7.4&hash=8133ad: Cannot apply hunk #2 (set enableInlineHunks for details)
> ➤ YN0000: └ Completed in 32s 30ms
> ➤ YN0000: Failed with errors in 38s 791ms```
> 
> ### Additional information
> 
> yarn --version
> 2.4.3
> 
> node --version
> v16.17.0
> 
> npm --version
> 8.15.0
> ```

Wgy don't use npm?

**Closed** 2024-09-18 18:40 UTC
Labels: :lady_beetle: confirmed bug, :stop_sign: wontfix
