### ISSUE TITLE
bug: Errors with clean T3 install

### ISSUE THREAD

**Issue by ScottyMaher** [t3-oss/create-t3-app#1961] opened 2024-08-10 02:20 UTC
### Provide environment information

  System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz        
    Memory: 5.50 GB / 15.89 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    bun: 1.1.22 - ~\.bun\bin\bun.EXE

  "ct3aMetadata": {
    "initVersion": "7.36.2"
  }

### Describe the bug

1. Create a completely fresh T3 app.
2. Fix invalid environment variables:
```
NEXTAUTH_SECRET="sample"
NEXTAUTH_URL="http://localhost:3000"

# Next Auth Discord Provider
DISCORD_CLIENT_ID="placeholder"
DISCORD_CLIENT_SECRET="placeholder"
```

3. Literally just open or refresh the localhost site in browser:

[TRPC] post.getLatest took 153ms to execute
A query that was dehydrated as pending ended up rejecting. [[["post","getLatest"],{"type":"query"}]]: TRPCError: UNAUTHORIZED; The error will be redacted in production builds
Error: redacted
    at eval (webpack-internal:///(rsc)/./node_modules/@tanstack/query-core/build/modern/hydration.js:37:31) {
  digest: '1184500366'
}
 GET / 200 in 8406ms
 ⨯ Internal error: Error: redacted
    at eval (./node_modules/@tanstack/query-core/build/modern/hydration.js:37:31)
digest: "1184500366"
 ⨯ unhandledRejection: Error: redacted
    at eval (webpack-internal:///(rsc)/./node_modules/@tanstack/query-core/build/modern/hydration.js:37:31) {
  digest: '1184500366'
}
 ⨯ unhandledRejection: Error: redacted
    at eval (webpack-internal:///(rsc)/./node_modules/@tanstack/query-core/build/modern/hydration.js:37:31) {
  digest: '1184500366'
}

### Reproduction repo

It's a fresh create t3-app@latest, with only the .env changed as described

### To reproduce

◇  Will you be using TypeScript or JavaScript?
│  TypeScript
│
◇  Will you be using Tailwind CSS for styling?
│  Yes
│
◇  Would you like to use tRPC?
│  Yes
│
◇  What authentication provider would you like to use?
│  NextAuth.js
│
◇  What database ORM would you like to use?
│  None (I also tried with Prisma)
│
◇  Would you like to use Next.js App Router?
│  Yes

### Additional information

I tried GPTing my way to a solution, but it was not helpful.

**Comment by lorenzobandini** [comment] 2024-08-10 22:23
> ### Provide environment information
> 
> System: OS: Windows 10 10.0.19045 CPU: (8) x64 Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz Memory: 5.50 GB / 15.89 GB Binaries: Node: 20.10.0 - C:\Program Files\nodejs\node.EXE bun: 1.1.22 - ~.bun\bin\bun.EXE
> 
> "ct3aMetadata": { "initVersion": "7.36.2" }
> ### Describe the bug
> 
>     1. Create a completely fresh T3 app.
> 
>     2. Fix invalid environment variables:
> 
> 
> ```
> NEXTAUTH_SECRET="sample"
> NEXTAUTH_URL="http://localhost:3000"
> 
> # Next Auth Discord Provider
> DISCORD_CLIENT_ID="placeholder"
> DISCORD_CLIENT_SECRET="placeholder"
> ```
> 
>     3. Literally just open or refresh the localhost site in browser:
> 
> 
> [TRPC] post.getLatest took 153ms to execute A query that was dehydrated as pending ended up rejecting. [[["post","getLatest"],{"type":"query"}]]: TRPCError: UNAUTHORIZED; The error will be redacted in production builds Error: redacted at eval (webpack-internal:///(rsc)/./node_modules/@tanstack/query-core/build/modern/hydration.js:37:31) { digest: '1184500366' } GET / 200 in 8406ms ⨯ Internal error: Error: redacted at eval (./node_modules/@tanstack/query-core/build/modern/hydration.js:37:31) digest: "1184500366" ⨯ unhandledRejection: Error: redacted at eval (webpack-internal:///(rsc)/./node_modules/@tanstack/query-core/build/modern/hydration.js:37:31) { digest: '1184500366' } ⨯ unhandledRejection: Error: redacted at eval (webpack-internal:///(rsc)/./node_modules/@tanstack/query-core/build/modern/hydration.js:37:31) { digest: '1184500366' }
> ### Reproduction repo
> 
> It's a fresh create t3-app@latest, with only the .env changed as described
> ### To reproduce
> 
> ◇ Will you be using TypeScript or JavaScript? │ TypeScript │ ◇ Will you be using Tailwind CSS for styling? │ Yes │ ◇ Would you like to use tRPC? │ Yes │ ◇ What authentication provider would you like to use? │ NextAuth.js │ ◇ What database ORM would you like to use? │ None (I also tried with Prisma) │ ◇ Would you like to use Next.js App Router? │ Yes
> ### Additional information
> 
> I tried GPTing my way to a solution, but it was not helpful.

i have the same errors

**Comment by lorenzocorallo** [comment] 2024-08-10 22:25
I'm getting something very similar (fresh setup with tRPC, NextAuth, Drizzle)

```
[TRPC] post.hello took 373ms to execute
[TRPC] post.getLatest took 120ms to execute
A query that was dehydrated as pending ended up rejecting. [[["post","getLatest"],{"type":"query"}]]: TRPCError: RequestInit: duplex option is required when sending a body.; The error will be redacted in production builds
 ⨯ Internal error: Error: redacted
    at eval (./node_modules/.pnpm/@tanstack+query-core@5.51.21/node_modules/@tanstack/query-core/build/modern/hydration.js:37:31)
digest: "2433427594"
Error: redacted
    at eval (webpack-internal:///(rsc)/./node_modules/.pnpm/@tanstack+query-core@5.51.21/node_modules/@tanstack/query-core/build/modern/hydration.js:37:31) {
  digest: '2433427594'
}
```

**Comment by lorenzocorallo** [comment] 2024-08-11 22:10
> I'm getting something very similar (fresh setup with tRPC, NextAuth, Drizzle)
> 
> ```
> [TRPC] post.hello took 373ms to execute
> [TRPC] post.getLatest took 120ms to execute
> A query that was dehydrated as pending ended up rejecting. [[["post","getLatest"],{"type":"query"}]]: TRPCError: RequestInit: duplex option is required when sending a body.; The error will be redacted in production builds
>  ⨯ Internal error: Error: redacted
>     at eval (./node_modules/.pnpm/@tanstack+query-core@5.51.21/node_modules/@tanstack/query-core/build/modern/hydration.js:37:31)
> digest: "2433427594"
> Error: redacted
>     at eval (webpack-internal:///(rsc)/./node_modules/.pnpm/@tanstack+query-core@5.51.21/node_modules/@tanstack/query-core/build/modern/hydration.js:37:31) {
>   digest: '2433427594'
> }
> ```

I could fix my issue by re-creating the project via an older version of `t3-app`, in particular the `7.34.0`.
I think that the issue is related to the changes introduced in the PR https://github.com/t3-oss/create-t3-app/pull/1932

**Comment by Guria** [comment] 2024-08-13 18:52
Newly created 7.36.2

```
>> query  #1 post.getLatest  { input: undefined }
[TRPC] post.getLatest took 355ms to execute
❌ tRPC failed on post.getLatest: UNAUTHORIZED
 GET /api/trpc/post.getLatest?batch=1&input=%7B%220%22%3A%7B%22json%22%3Anull%2C%22meta%22%3A%7B%22values%22%3A%5B%22undefined%22%5D%7D%7D%7D 200 in 372ms
 << query  #1 post.getLatest  {
  input: undefined,
  result: TRPCClientError: UNAUTHORIZED
      at TRPCClientError.from (webpack-internal:///(ssr)/./node_modules/@trpc/client/dist/TRPCClientError.mjs:40:20)
      at eval (webpack-internal:///(ssr)/./node_modules/@trpc/client/dist/links/httpBatchStreamLink.mjs:125:106)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
    meta: {
      response: Response {
        status: 200,
        statusText: 'OK',
        headers: Headers {
          vary: 'RSC, Next-Router-State-Tree, Next-Router-Prefetch, trpc-accept',
          'content-type': 'application/json',
          'transfer-encoding': 'chunked',
          date: 'Tue, 13 Aug 2024 18:40:43 GMT',
          connection: 'keep-alive',
          'keep-alive': 'timeout=5'
        },
        body: ReadableStream { locked: true, state: 'readable', supportsBYOB: true },
        bodyUsed: true,
        ok: true,
        redirected: false,
        type: 'basic',
        url: 'http://localhost:3000/api/trpc/post.getLatest?batch=1&input=%7B%220%22%3A%7B%22json%22%3Anull%2C%22meta%22%3A%7B%22values%22%3A%5B%22undefined%22%5D%7D%7D%7D'
      }
    },
    shape: { message: 'UNAUTHORIZED', code: -32001, data: [Object] },
    data: {
      code: 'UNAUTHORIZED',
      httpStatus: 401,
      stack: 'TRPCError: UNAUTHORIZED\n' +
        '    at eval (webpack-internal:///(rsc)/./src/server/api/trpc.ts:111:15)\n' +
        '    at callRecursive (webpack-internal:///(rsc)/./node_modules/@trpc/server/dist/unstable-core-do-not-import/procedureBuilder.mjs:160:38)\n' +
        '    at next (webpack-internal:///(rsc)/./node_modules/@trpc/server/dist/unstable-core-do-not-import/procedureBuilder.mjs:169:32)\n' +
        '    at eval (webpack-internal:///(rsc)/./src/server/api/trpc.ts:90:26)\n' +
        '    at async callRecursive (webpack-internal:///(rsc)/./node_modules/@trpc/server/dist/unstable-core-do-not-import/procedureBuilder.mjs:160:32)\n' +
        '    at async procedure (webpack-internal:///(rsc)/./node_modules/@trpc/server/dist/unstable-core-do-not-import/procedureBuilder.mjs:190:24)\n' +
        '    at async eval (webpack-internal:///(rsc)/./node_modules/@trpc/server/dist/unstable-core-do-not-import/http/resolveResponse.mjs:207:30)\n' +
        '    at async eval (webpack-internal:///(rsc)/./node_modules/@trpc/server/dist/unstable-core-do-not-import/http/resolveResponse.mjs:359:45)',
      path: 'post.getLatest',
      zodError: null
    },
    [cause]: undefined
  },
  elapsedMs: 388
}
 ⨯ Internal error: TRPCClientError: UNAUTHORIZED
    at TRPCClientError.from (./node_modules/@trpc/client/dist/TRPCClientError.mjs:40:20)
    at eval (./node_modules/@trpc/client/dist/links/httpBatchStreamLink.mjs:125:106)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
digest: "4169396856"
 GET / 500 in 1242ms
```

**Comment by eltonstewart** [comment] 2024-08-14 04:54
that worked for me too @Guria

**Comment by ryanhell** [comment] 2024-08-14 21:39
can confirm adding await to line #11 of page.tsx inside the app folder; also worked for me to eliminate this error message. Will check back to see if there is any new information..

**Comment by Guria** [comment] 2024-08-16 10:26
@eltonstewart @ryanhell Please don't treat it as long term fix.
Adding await here changes expected behaviour. General idea is just trigger getting result at early stage, but don't block page loading and return Suspense fallback.

This issue still requires investigation and proper long term fix. Personally I decided to bootstrap with 7.34 version.

**Comment by NightClover-code** [comment] 2024-08-17 22:20
Just had this exact same error and @Guria's temporary fix works for me.

**Comment by lorenzocorallo** [comment] 2024-08-19 16:52
> @eltonstewart @ryanhell @NightClover-code @ScottyMaher @lorenzocorallo 
> 
> can you share which DB adapter have you used? Drizzle or Prisma?

I'm using Drizzle with a Turso database

**Comment by Guria** [comment] 2024-08-19 17:03
Hmm. With latest 7.37 I have this issue with Postgres + Prisma, and no issue with Postgres + Drizzle.

**Comment by Guria** [comment] 2024-08-19 17:10
Ok, I've found the descrepancy. 
One template use `getLatest: protectedProcedure.query` and another one `getLatest: publicProcedure.query`.
So proper solution is just either use `publicProcedure` for getLatest or do not await protectedVersion in signed out state.
I will prepare a fix for affected templates.

**Comment by electroheadfx** [comment] 2024-09-02 17:49
I have the same issue !

**Comment by Guria** [comment] 2024-09-03 06:24
@electroheadfx just make prefetch conditional based on session. See #1969

**Comment by juliusmarminge** [comment] 2024-10-03 10:51
Closed by https://github.com/t3-oss/create-t3-app/pull/1969

**Closed** 2024-10-03 10:51 UTC
Labels: 🐞❔ unconfirmed bug

**Comment by Code-Victor** [comment] 2025-05-08 14:52
Please is there a way to handle errors on the client instead? with useSuspense?

**Comment by Code-Victor** [comment] 2025-05-08 15:00
Here's my code:
/app/layout.tsx

```tsx
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  void api.user.me.prefetch();

  return (
    <html lang="en" className={`${dDin.variable}`} suppressHydrationWarning>
      <body className="bg-background text-foreground font-d-din">
        <Providers>
          <HydrateClient>
            <Navbar />
          </HydrateClient>
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
```
in the user-button in the navbar component:
```tsx
  const [user, { error }] = api.user.me.useSuspenseQuery(undefined, {
    select(data) {
      return data.data;
    },
  });
```

Here's the error I keep getting:

![Image](https://github.com/user-attachments/assets/10c2022b-c479-403b-aa9f-665ba1801827)
is it possible to handle the error in the User-button component?
