### ISSUE TITLE
bug: Running create-t3-app on current folder (".") breaks default settings

### ISSUE THREAD

**Issue by TheDevilOnLine** [t3-oss/create-t3-app#1926] opened 2024-07-02 10:25 UTC
### Provide environment information

  System:
    OS: Windows 11 10.0.22631
    CPU: (24) x64 AMD Ryzen 9 7900X 12-Core Processor
    Memory: 58.33 GB / 95.21 GB
  Binaries:
    Node: 20.12.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.21 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.8.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.7.4 - ~\AppData\Local\pnpm\pnpm.CMD
    bun: 1.1.7 - ~\.bun\bin\bun.EXE

### Describe the bug

When you run `npx create-t3-app@latest .` some parts of the configuration break. For example the `DATABASE_URL` is set to `mysql://root:password@localhost:3306/.`.

Suggested fix is to read the `name` from `package.json` and use that for the database name.

### Reproduction repo

N/A

### To reproduce

Just run `npx create-t3-app@latest .`

**Comment by juliusmarminge** [comment] 2024-07-04 21:56
Duplicate of https://github.com/t3-oss/create-t3-app/issues/1919

**Closed by juliusmarminge** 2024-07-04 21:56 UTC
Labels: :beginner: good first issue, 🐞❔ unconfirmed bug, 👨‍👦‍👦free for all
