### ISSUE TITLE
bug: Vercel Standard Deployment Proteciton breaks tRPC

### ISSUE THREAD

**Issue by nemanjastanic** [t3-oss/create-t3-app#1648] opened 2023-11-06 14:25 UTC
### Provide environment information

System:
    OS: macOS 14.0
    CPU: (8) arm64 Apple M1
    Memory: 107.31 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
    pnpm: 8.6.2 - /opt/homebrew/bin/pnpm
    bun: 0.7.3 - /opt/homebrew/bin/bun

### Describe the bug

When you use Standard Deployment Protection (default and recommended by Vercel), `VERCEL_URL` is now undefined. This breaks tRPC since the `getUrl` function falls back to `http://localhost:3000`.

This is due to a recent change [(Vercel Docs)](https://vercel.com/docs/security/deployment-protection#migrating-to-standard-protection)

### Reproduction repo

Unnecessary

### To reproduce

1. Create a new app using create-t3-app
2. Deploy it to Vercel
3. Make sure deployment protection stays on `Standard Protection`
4. All tRPC requests will result in a server-side exception

**Comment by sscotth** [comment] 2023-11-06 19:34
Looks like a dupe of #1639

**Comment by juliusmarminge** [comment] 2023-11-21 22:54
server calls no longer use http so i believe this issue is "automatically" resolved - reopen if you still have issues

**Closed by juliusmarminge** 2023-11-21 22:54 UTC
Labels: 🐞❔ unconfirmed bug
