### ISSUE TITLE
feat: use baseUrl and paths for imports

### ISSUE THREAD

**Issue by shobhitic** [t3-oss/create-t3-app#894] opened 2022-11-29 04:03 UTC
### Is your feature request related to a problem? Please describe.

Not a problem, but the imports like

```typescript
import { prisma } from "../../../server/db/client";
```

feel a little disorienting. Other frameworks like Redwood have moved to using typescript paths to solve them.

### Describe the solution you'd like to see

Paths are a typescript compilation option ([see here](https://www.typescriptlang.org/tsconfig#paths)) in the tsconfig file with which we can use something like 

```typescript
import { prisma } from "src/server/db/client";
```

in place of 

```typescript
import { prisma } from "../../../server/db/client";
```

To do this, we need to define `baseUrl` and `paths` object in tsconfig file, and then change the imports.

### Describe alternate solutions

Alternate would be to go forward with what is available right now and don't change it.

### Additional information

Happy to work on a PR for this.

**Comment by nexxeln** [comment] 2022-11-29 05:18
Please search for existing issues before making one. Duplicate of https://github.com/t3-oss/create-t3-app/pull/51, https://github.com/t3-oss/create-t3-app/issues/85, https://github.com/t3-oss/create-t3-app/pull/144, https://github.com/t3-oss/create-t3-app/issues/188.

**Closed by nexxeln** 2022-11-29 05:18 UTC
Labels: 🌟 enhancement
