### ISSUE TITLE
bug: create t3-app does initialises with javascript files

### ISSUE THREAD

**Issue by acewf** [t3-oss/create-t3-app#1331] opened 2023-04-03 15:18 UTC
### Provide environment information

  System:
    OS: macOS 13.3
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 397.86 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/np

    
    "ct3aMetadata": {
      "initVersion": "7.10.2"
    }

### Describe the bug

Although my choice was javascript from the setup prompt, project files been set in typescript.  

### Reproduction repo

n/a

### To reproduce

npm create t3-app@latest

? What will your project be called? my-t3-app
? Will you be using TypeScript or JavaScript? JavaScript
Wrong answer, using TypeScript instead...
? Which packages would you like to enable? tailwind, trpc
? Initialize a new git repository? Yes
Nice one! Initializing repository!
? Would you like us to run 'npm install'? Yes
Alright. We'll install the dependencies for you!
? What import alias would you like configured? ~/

Using: npm

✔ my-t3-app scaffolded successfully!

Adding boilerplate...
✔ Successfully setup boilerplate for tailwind
✔ Successfully setup boilerplate for trpc
✔ Successfully setup boilerplate for envVariables

Installing dependencies...
✔ Successfully installed dependencies!

Initializing Git...
✔ Successfully initialized and staged git

**Comment by c-ehrlich** [comment] 2023-04-03 15:32
Duplicate of https://github.com/t3-oss/create-t3-app/issues/117

**Closed by c-ehrlich** 2023-04-03 15:32 UTC
Labels: 🐞❔ unconfirmed bug
