### ISSUE TITLE
Layout shifting caused by block's changing size on hover

### ISSUE THREAD

**Issue by mnik01** [t3-oss/create-t3-app#90] opened 2022-07-04 02:35 UTC
**Describe the bug**
When the browser is in full-screened (via F11 or just stretched window at all screen) you can point the mouse to the right corner of the screen
And because tRPC block scales up on hover, scrollbars appear and deactivate hover. And this will be repeated.

**To Reproduce**
- Make page/browser to full screen
- Point your mouse to right-center point

**Expected behavior**
To have x-paddings for these blocks or do not trigger scrollbar appearing 

**Screenshots**
![bug](https://user-images.githubusercontent.com/39025497/177071990-9fd68a5c-3e67-4634-9135-91548aea42a9.gif)

**Comment by nexxeln** [comment] 2022-07-04 03:28
Thank you for opening this issue. Will take a look at this in a bit.

**Comment by robertmcabee** [comment] 2022-07-04 05:15
Unable to replicate - what browser and os is this appearing on?

**Comment by mnik01** [comment] 2022-07-04 13:54
Here's a video of reproducing 
https://www.loom.com/share/50fe24ee6abc4d5095a2236000a1ccf8

**Comment by asheeeshh** [comment] 2022-07-04 18:13
cant reproduce

**Comment by asheeeshh** [comment] 2022-07-05 09:50
should have been fixed by the new UI #115  , can be closed @nexxeln

**Closed** 2022-07-05 09:51 UTC
Labels: bug
