### ISSUE TITLE
Project root TypeScript import path alias

### ISSUE THREAD

**Issue by NuroDev** [t3-oss/create-t3-app#198] opened 2022-07-14 23:22 UTC
**Is your feature request related to a problem? Please describe.**

In terms of code maintainability, I don't know about others but the sight of `../../../components/`, etc is an eyesore that could be very easily be solved using the TypeScript config.

**Describe the solution you'd like**
Currently the simplest & easiest solution, and one that I use myself but of course is open to discussion on what everyone thinks might be best, would be to add the following to the `tsconfig.json` to add a project root import alias (EG: `~/components`)
```json
{
	"compilerOptions": {
		"baseUrl": ".",
		"paths": {
			"~/*": ["./src/*"]
		}
	}
}
```

**Describe alternatives you've considered**
There may be some alternative solutions solutions for import aliases but I feel like utilizing the `paths` function from TypeScript seems like the simplest & most straight forward.

That said the character used for the project root alias is open for discussion on what everyone think might be best. In my case I recommend using the `~` character as it's both already started to get [popularised by Remix](https://github.com/remix-run/remix/blob/main/examples/basic/tsconfig.json#L14-L17) & in Unix as it references the users home directory.

**Comment by juliusmarminge** [comment] 2022-07-14 23:32
Duplicate of #51, #85, #144, #188.

We like the idea of path aliases but we have decided it is too opinionated and everyone implements them differently and would have to go and make modifications either way to suit their needs.

**Closed by juliusmarminge** 2022-07-14 23:32 UTC
