### ISSUE TITLE
Bug: Vercel deployment results in TypeError: Cannot read properties of null (reading 'useMemo')

### ISSUE THREAD

**Issue by pavan38kp** [t3-oss/create-t3-app#1399] opened 2023-05-04 18:29 UTC
### Provide environment information

  System:
    OS: macOS 11.6.1
    CPU: (8) arm64 Apple M1
    Memory: 112.23 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.13.0 - /usr/local/bin/node
    Yarn: 1.22.17 - ~/.yarn/bin/yarn
    npm: 8.19.3 - /usr/local/bin/npm

### Describe the bug

This issue occurs when an attempt is made to deploy the application on Vercel.

![image](https://user-images.githubusercontent.com/89772306/236294900-3741dbf9-aab0-4998-9cc1-0fb1b89e69f4.png)
![image](https://user-images.githubusercontent.com/89772306/236294991-f7453aef-4297-4e35-8164-868f9a0e3553.png)

### Reproduction repo

https://github.com/pavankpdev/sica

### To reproduce

1. Fork/Clone the repo - This is actually a fresh installation if T3
2. deploy with vercel

### Additional information

1. I created a new T3 app project to check if my project was causing the issue. 
2. However, I discovered that even the new T3 app fails to deploy with similar issues.

**Comment by tonyno** [comment] 2023-05-04 19:05
Having same issue :-(

**Comment by c-ehrlich** [comment] 2023-05-04 19:39
I can reproduce the issue with your repo, but it does not happen on one I created myself with the same version/packages:

https://github.com/c-ehrlich/test2

https://test2-vert-one.vercel.app/

Can you confirm that you're able to deploy my repo?

**Comment by pavan38kp** [comment] 2023-05-04 19:56
> I can reproduce the issue with your repo, but it does not happen on one I created myself with the same version/packages:
> 
> https://github.com/c-ehrlich/test2
> 
> https://test2-vert-one.vercel.app/
> 
> Can you confirm that you're able to deploy my repo?

Strange I was able to deploy it with your repo. Can you try to reproduce with my repo using `main` branch

**Comment by michalbundyra** [comment] 2023-05-04 19:59
@pavan38kp @c-ehrlich maybe it works because it is fixed with `+ next 13.2.4`. The problem is since next 13.4.0, I have the same on my project when renovate created PRs to update to 13.4.0

**Comment by pavan38kp** [comment] 2023-05-04 20:02
> @pavan38kp @c-ehrlich maybe it works because it is fixed with `+ next 13.2.4`. The problem is since next 13.4.0, I have the same on my project when renovate created PRs to update to 13.4.0

So upgrading to 13.4 would help?

**Comment by michalbundyra** [comment] 2023-05-04 20:04
@pavan38kp 

> So upgrading to 13.4 would help?

If by "help" you mean reproduce the reported issue - then yes ;-)

**Comment by pavan38kp** [comment] 2023-05-04 20:08
> @pavan38kp
> 
> > So upgrading to 13.4 would help?
> 
> If by "help" you mean reproduce the reported issue - then yes ;-)

Alrught, I'm trying this now.

**Comment by pavan38kp** [comment] 2023-05-04 20:15
Well, I tried to reproduce with next `13.4`, and it still fails with the same issues. :(
@michalbundyra

**Comment by tonyno** [comment] 2023-05-04 20:30
I tried to upgrade to latest version of all libraries, but it didn't help either.
Repo: https://github.com/tonyno/my-t3-app

Upgrade:
```
npm i -g npm-check-updates
ncu -u
npm install
```

**Comment by michalbundyra** [comment] 2023-05-04 21:20
See also https://github.com/trpc/trpc/issues/4316

**Comment by esthevann** [comment] 2023-05-04 22:37
Same issue here with a fresh template https://github.com/esthevann/chirp

**Comment by baseba** [comment] 2023-05-05 01:43
As said by @c-ehrlich just change in your dependencies in package.json
`"next": "^13.2.4"` to `"next": "13.2.4"`
This should do the work while there is a definitive fix

**Comment by thefirebanks** [comment] 2023-05-05 06:13
> As said by @c-ehrlich just change in your dependencies in package.json
"next": "^13.2.4" to "next": "13.2.4"
This should do the work while there is a definitive fix

Can confirm that this worked for me!

**Comment by pavan38kp** [comment] 2023-05-05 09:27
yes Thanks @baseba it works now

**Comment by c-ehrlich** [comment] 2023-05-05 09:29
Can confirm that it's caused by this https://github.com/trpc/trpc/issues/4316

Let's pin Next to 13.2.4 until that is fixed. I'm writing the pr now and will subscribe to the issue so that we can undo the pinning asap.

Thanks @pavan38kp @michalbundyra for finding and profiling this.

Will leave this open for the time being so that people who have scaffolded with the bug can see it :)

**Comment by michalbundyra** [comment] 2023-05-05 09:32
@c-ehrlich 13.3.4 is also fine, the problem is only with 13.4.0, any previous version works fine.

**Comment by michalbundyra** [comment] 2023-05-05 12:53
Seems to be fixed now with NextJS 13.4.1 - probably in https://github.com/vercel/next.js/pull/49274

**Comment by belgattitude** [comment] 2023-05-05 12:56
I can confirm as well - tested in https://github.com/belgattitude/nextjs-monorepo-example/pull/3775

**Closed** 2023-05-06 11:50 UTC
Labels: :lady_beetle: upstream bug

**Comment by meetqy** [comment] 2023-05-17 09:04
> @c-ehrlich 13.3.4 is also fine, the problem is only with 13.4.0, any previous version works fine.

Yeah, i can use 13.3.4, Not problem.
