### ISSUE TITLE
bug: NextAuth session is undefined when passed as a prop from getServerSideProps 

### ISSUE THREAD

**Issue by matibox** [t3-oss/create-t3-app#1039] opened 2023-01-02 16:20 UTC
#### System:
- OS: Linux 5.10 Ubuntu 20.04.5 LTS (Focal Fossa)
- CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
- Memory: 6.50 GB / 7.74 GB
- Container: Yes
- Shell: 5.0.17 - /bin/bash
#### Binaries:
- Node: 18.0.0 - ~/.nvm/versions/node/v18.0.0/bin/node
- npm: 8.6.0 - ~/.nvm/versions/node/v18.0.0/bin/npm

*Note: I'm using Windows Subsystem for Linux*

### Describe the bug

```tsx
const NewRecipe: NextPage<
  InferGetServerSidePropsType<typeof getServerSideProps>
> = ({ session }) => {
  const router = useRouter();

  console.log(session); // this logs undefined to the console

  return (
    <div className='h-[calc(100vh_-_var(--navbar-height))] border-t border-beige bg-black p-6'>
      <Button handleClick={() => router.back()} variant='secondary'>
        <span>back</span>
      </Button>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps<{
  session: Session;
}> = async ctx => {
  const session = await getServerAuthSession(ctx);

  if (!session) {
    return {
      redirect: {
        destination: '/',
        permanent: false,
      },
    };
  }

  console.log(session); // this logs session data to the console

  return {
    props: {
      session,
    },
  };
};
```

### console.log result from getServerSideProps

![image](https://user-images.githubusercontent.com/47917952/210255120-565b9bf6-b18c-4449-8fbd-eec64a541a0d.png)

### console.log result from NewRecipe page

![image](https://user-images.githubusercontent.com/47917952/210255348-837ee6e0-2963-41d0-a59a-0d98c948124e.png)

### To reproduce

```tsx
import {
  type InferGetServerSidePropsType,
  type GetServerSideProps,
  type NextPage,
} from 'next';
import { type Session } from 'next-auth';

const Page: NextPage<InferGetServerSidePropsType<typeof getServerSideProps>> = ({ session }) => {
  console.log(session);
  return <div>content</div>;
}

export const getServerSideProps: GetServerSideProps<{ session: Session | null }> = async ctx => {
  const session = await getServerAuthSession(ctx);

  console.log(session);

  return {
    props: {
      session
    }
  }
}

```

### Additional information

I am using the stack for the first time and I have no idea if my approach is right. But the issue gets fixed when I do this in ```_app.tsx```

```tsx
const MyApp: AppType<{ session: Session | null}> =({
  Component,
  pageProps
}) => {
  const { session } = pageProps;

  return ( 
    <SessionProvider session={session}>
      <Component {...pageProps} />
    </SessionProvider>
  )
}
```

instead of this

```tsx
const MyApp: AppType<{ session: Session | null}> =({
  Component,
  pageProps: {session, ...pageProps}
}) => {
  return ( 
    <SessionProvider session={session}>
      <Component {...pageProps} />
    </SessionProvider>
  )
}
```

**Comment by juliusmarminge** [comment] 2023-01-03 09:32
Reproduced here: https://github.com/juliusmarminge/session-gssp

**Comment by matibox** [comment] 2023-01-03 13:24
Thanks, should I close the issue or it gets automatically closed when linked PR is closed? I'm contributing for the first time :D

**Comment by juliusmarminge** [comment] 2023-01-03 13:25
> Thanks, should I close the issue or it gets automatically closed when linked PR is closed? I'm contributing for the first time :D

It will be closed once the PR is merged.

Thanks for your contribution 🙏🏼

**Comment by matibox** [comment] 2023-01-03 13:38
Okay, thanks for the help!

**Comment by matibox** [comment] 2023-01-03 15:50
I just realised I should do this like this instead of passing a session as a prop. I got confused by NextAuth docs example https://next-auth.js.org/configuration/nextjs#in-getserversideprops, I thought I can pull the session prop like usual. Sorry for the inconvenience.

```tsx
export const Page: NextPage = () => {
  const { data: session } = useSession();
}

export const getServerSideProps: GetServerSideProps<{
  session: Session | null;
}> = async ctx => {
  return {
    props: {
      session: await getServerAuthSession(ctx),
    },
  };
};
```

**Comment by juliusmarminge** [comment] 2023-01-03 15:53
> I just realised I should do this like this instead of passing a session as a prop. I got confused by NextAuth docs example https://next-auth.js.org/configuration/nextjs#in-getserversideprops, I thought I can pull the session prop like usual. Sorry for the inconvenience.
> 
> ```tsx
> export const Page: NextPage = () => {
>   const { data: session } = useSession();
> }
> 
> export const getServerSideProps: GetServerSideProps<{
>   session: Session | null;
> }> = async ctx => {
>   return {
>     props: {
>       session: await getServerAuthSession(ctx),
>     },
>   };
> };
> ```

Yea Balazs recommended this approach in my upstream issue.

I think it might be a bit cursed to pull out the prop since now the session prop doesn't behave as any other prop you pass down from gSSP - although the hook pattern is generally better and will make sure the session stays up to date too - whilst being prefetched on the server.

I've changed the PR to be a doc change which will show this pattern

**Comment by matibox** [comment] 2023-01-03 16:10
Yeah definitely the hook approach makes more sense. That should be highlighted in T3 docs and NextAuth docs as well cause it's confusing - usually with gSSP you pass the props object and destructure it in page props.

**Closed** 2023-01-06 13:26 UTC
Labels: :lady_beetle: confirmed bug, 📌 area: t3-app
