### ISSUE TITLE
Wrong answer, using TypeScript instead...

### ISSUE THREAD

**Issue by iamgmd** [t3-oss/create-t3-app#117] opened 2022-07-05 08:41 UTC
When choosing, 'Javascript' on the question 'Will you be using JavaScript or TypeScript?', an error of 'Wrong answer, using Typescript instead...' is displayed and 'Typescript' is automatically chosen.

1. npx create-t3-app@latest
2. Choose desired project name
3. Select Javascript as being the preferred language.

Expected, the project to be scaffolded in Javascript.

![2022-07-05-09-43-21](https://user-images.githubusercontent.com/2772038/177288014-98373922-5f48-4dbe-a220-a7473ce82f34.png)

![2022-07-05-09-44-03](https://user-images.githubusercontent.com/2772038/177288144-cacae019-81b6-43e9-a1bf-32377a220bf2.png)

Using Macbook Pro M1 Max with node v16.15.1

**Comment by nexxeln** [comment] 2022-07-05 08:52
This behavior is intended as we believe you shouldn't use JavaScript in combination with the T3 stack

**Comment by TheoBr** [comment] 2022-07-05 08:56
Closing per [Axiom 3](https://github.com/t3-oss/create-t3-app)

**Comment by Dhravya** [comment] 2022-07-05 08:57
That's the point right, the entire stack is (in order to follow the axioms), typesafe-only

**Closed** 2022-07-05 08:56 UTC

**Comment by fernandoxu** [comment] 2022-07-07 01:57
It’s a feature, not a bug🤪

**Comment by prabhathk14411** [comment] 2023-04-13 06:51
> Closing per [Axiom 3](https://github.com/t3-oss/create-t3-app)

Then why provide an option to choose between Typescript and Javascript.

**Comment by fernandoxu** [comment] 2023-04-13 06:53
> > Closing per [Axiom 3](https://github.com/t3-oss/create-t3-app)
> 
> Then why provide an option to choose between Typescript and Javascript.

just for fun,I guess🤪
