### ISSUE TITLE
docs: Sometimes theme switch doesn't affect the sidebar

### ISSUE THREAD

**Issue by LakeQueen** [t3-oss/create-t3-app#864] opened 2022-11-25 09:46 UTC
### Provide environment information

![image](https://user-images.githubusercontent.com/40394423/203949393-a0277ef4-4727-466e-abb3-b41f37bdff55.png)

### Describe the bug

When selecting dark or light theme in the documentation, ocassionally the sidebar doesn't register the change (typically the first time).

### To reproduce

Toggle the light/dark theme switch. This bug happened when I toggled it just once, but you can reliably reproduce it by toggling it on and off multiple times very fast.

**Comment by nexxeln** [comment] 2022-11-25 10:17
Not able to reproduce on my end

**Comment by LakeQueen** [comment] 2022-11-25 11:38
Interesting. I can only reproduce it in Chrome. In Firefox and Brave works like it should.

**Comment by nexxeln** [comment] 2022-11-25 13:29
> Interesting. I can only reproduce it in Chrome. In Firefox and Brave works like it should.

On Chrome

![brave_PIO3BtYiX4](https://user-images.githubusercontent.com/95541290/203995648-1afbe3ea-ce3f-4d94-8a1e-d1585b7cf04b.gif)

**Comment by c-ehrlich** [comment] 2022-11-25 17:29
> Interesting. I can only reproduce it in Chrome. In Firefox and Brave works like it should.

i can't reproduce this either.

what OS / version of chrome are you on, and does it also happen in an incognito tab?

**Comment by Leweyse** [comment] 2022-11-26 10:09
In Firefox, I noticed that the background of the navigation bar and the left sidebar differ slightly from the body background when changing the theme:

![ct3-app](https://user-images.githubusercontent.com/69996340/204082821-6215bb2e-02c7-4c8c-b043-a9201569bf65.gif)

**Comment by nexxeln** [comment] 2022-11-26 10:35
> In Firefox, I noticed that the background of the navigation bar and the left sidebar differ slightly from the body background when changing the theme:

That's because of our animation

**Comment by juliusmarminge** [comment] 2022-11-26 16:52
> > In Firefox, I noticed that the background of the navigation bar and the left sidebar differ slightly from the body background when changing the theme:
> 
> 
> 
> That's because of our animation

Hmm weird I think everything should have the same duration?

**Comment by c-ehrlich** [comment] 2022-11-26 19:34
> > > In Firefox, I noticed that the background of the navigation bar and the left sidebar differ slightly from the body background when changing the theme:
> > 
> > 
> > That's because of our animation
> 
> Hmm weird I think everything should have the same duration?

I can reproduce this in current Firefox on MacOS, though not as extreme as in the gif above. Maybe Firefox prioritises the body for animations or something like that?

**Comment by Leweyse** [comment] 2022-11-26 21:32
> > > > In Firefox, I noticed that the background of the navigation bar and the left sidebar differ slightly from the body background when changing the theme:
> > > 
> > > 
> > > That's because of our animation
> > 
> > 
> > Hmm weird I think everything should have the same duration?
> 
> I can reproduce this in current Firefox on MacOS, though not as extreme as in the gif above. Maybe Firefox prioritises the body for animations or something like that?

I think it can be fixed by removing the background color:

![docs_layout](https://user-images.githubusercontent.com/69996340/204109493-556b0f6e-faa3-4567-aabe-bbe471886ffd.png)

This is on my local after removing that property for the navbar and left sidebar, but keeping it for the body.

![local](https://user-images.githubusercontent.com/69996340/204109660-79fe83d3-eaca-4f35-9ca3-382804381d6c.gif)

Is it necessary to open a PR for this?

**Comment by c-ehrlich** [comment] 2022-11-27 10:26
> > > > > In Firefox, I noticed that the background of the navigation bar and the left sidebar differ slightly from the body background when changing the theme:
> > > > 
> > > > 
> > > > That's because of our animation
> > > 
> > > 
> > > Hmm weird I think everything should have the same duration?
> > 
> > 
> > I can reproduce this in current Firefox on MacOS, though not as extreme as in the gif above. Maybe Firefox prioritises the body for animations or something like that?
> 
> I think it can be fixed by removing the background color:
> 
> ![docs_layout](https://user-images.githubusercontent.com/69996340/204109493-556b0f6e-faa3-4567-aabe-bbe471886ffd.png)
> 
> This is on my local after removing that property for the navbar and left sidebar, but keeping it for the body.
> 
> ![local](https://user-images.githubusercontent.com/69996340/204109660-79fe83d3-eaca-4f35-9ca3-382804381d6c.gif) [ ![local](https://user-images.githubusercontent.com/69996340/204109660-79fe83d3-eaca-4f35-9ca3-382804381d6c.gif) ](https://user-images.githubusercontent.com/69996340/204109660-79fe83d3-eaca-4f35-9ca3-382804381d6c.gif) [ ](https://user-images.githubusercontent.com/69996340/204109660-79fe83d3-eaca-4f35-9ca3-382804381d6c.gif)
> 
> Is it necessary to open a PR for this?

Feel free to open a pr for this if it doesn't cause regressions anywhere else

**Comment by c-ehrlich** [comment] 2022-11-27 10:27
Also closing this because the discussion is far removed from the original issue

**Closed by c-ehrlich** 2022-11-27 10:27 UTC
Labels: 🐞❔ unconfirmed bug, 🚫 cant reproduce
