### ISSUE TITLE
bug:  Cannot set the NEXTAUTH_SECRET Environment Variable

### ISSUE THREAD

**Issue by ahmetkca** [t3-oss/create-t3-app#484] opened 2022-09-20 01:28 UTC
### Provide environment information

  System:
    OS: Linux 5.10 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
    Memory: 20.61 GB / 25.00 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.asdf/installs/nodejs/16.16.0/bin/node
    Yarn: 1.22.15 - ~/.asdf/installs/nodejs/16.16.0/bin/yarn
    npm: 8.15.1 - ~/.asdf/plugins/nodejs/shims/npm

### Describe the bug

I cannot set the environment variable `NEXTAUTH_SECRET`. However, I can set any other environment variable.

### To reproduce

I just created a brand new project didn't install anything new. So i don't know if it is even reproducible or is it just a problem with my pc which I don't think it is because I can set any other environment variable just not `NEXTAUTH_SECRET'

**Comment by benmarg** [comment] 2022-09-20 01:30
What error do you try to get when you try and set the variable?

**Comment by c-ehrlich** [comment] 2022-09-20 07:53
what is the ct3a version in package.json? and could you maybe post a minimal reproduction?

**Comment by thanhtutzaw** [comment] 2022-09-21 06:45
Why you want to set  ?
If you are useing NextAuth Library , I think you don't need that for auth . 
https://next-auth.js.org/configuration/options#secret

**Comment by c-ehrlich** [comment] 2022-10-02 20:52
Closing due to lack of reproduction. Feel free to reopen if you can provide more details.

**Closed by c-ehrlich** 2022-10-02 20:52 UTC
Labels: 🐞❔ unconfirmed bug
